# Generated by Django 3.0.6 on 2020-05-27 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_listorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default='0', verbose_name='Цена')),
                ('text', models.CharField(default='', max_length=200, verbose_name='Комментария')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.Products', verbose_name='Продукт ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь ID')),
            ],
            options={
                'verbose_name': 'Комментария',
                'verbose_name_plural': 'Коментария',
            },
        ),
    ]
