# Generated by Django 3.0.6 on 2020-05-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.IntegerField(default='0', verbose_name='Статус'),
        ),
    ]
